import { IHerbalItem } from './ViewModel'
export const classifyTitle: string[] = [
  "全部",
  "分类",
  "分类",
  "分类",
  "分类",
  "分类",
  "分类",
  "分类",
  "分类",
  "分类",
  "分类",
  "分类",
  "分类",
  "分类",
  "分类",
  "分类",
  "分类",
  "分类",
]

export const herbalInfo: Array<IHerbalItem> = [
  {
    name: '阿魏',
    image: $r('app.media.yc_awei'),
    price: 100,
    class: '树脂类'
  },
  {
    name: '阿魏',
    image: $r('app.media.yc_awei'),
    price: 100,
    class: '树脂类'
  },
  {
    name: '阿魏',
    image: $r('app.media.yc_awei'),
    price: 100,
    class: '树脂类'
  },
  {
    name: '阿魏',
    image: $r('app.media.yc_awei'),
    price: 100,
    class: '树脂类'
  },
]