import { IHerbalModel } from './ViewModel'
export const classifyTitle: string[] = [
  "全部",
  "分类",
  "分类",
  "分类",
  "分类",
  "分类",
  "分类",
  "分类",
  "分类",
  "分类",
  "分类",
  "分类",
  "分类",
  "分类",
  "分类",
  "分类",
  "分类",
  "分类",
]

export const herbalInfo: Array<IHerbalModel> = [
  {
    id: 1,
    name: '阿魏',
    image: $r('app.media.yc_awei'),
    price: 100,
    class: '树脂类'
  },
  {
    id: 2,
    name: '阿魏',
    image: $r('app.media.yc_awei'),
    price: 100,
    class: '树脂类'
  },
  {
    id: 3,
    name: '阿魏',
    image: $r('app.media.yc_awei'),
    price: 100,
    class: '树脂类'
  },
  {
    id: 4,
    name: '阿魏',
    image: $r('app.media.yc_awei'),
    price: 100,
    class: '树脂类'
  },
]