/**
    Constants for color
 */
export class ColorConstants {
    /**
     color for placeholder
     */
    static readonly PLACEHOLDER: number = 0x999999;
    /**
     * color green
     */
    static readonly GREEN_MINT: number = 0xDAFFED;
    static readonly GREEN_LIGHT: number = 0xADFC92;
    static readonly GREEN_DEEP: number = 0x7A8450;
    /**
     * color grey
     */
    static readonly GREY_DEEP: number = 0xC1CAD6;
    static readonly GREY_LIGHT: number = 0xDDE1E4;
    /**
     * color red
     */
    static readonly RED: number = 0xB80C09;
}