/**
    Constants for style
 */
export class StyleConstants {
    /**
     输入的最大长度
     */
    static readonly USERNAME_MAX_LENGTH: number = 6
    static readonly PASSWORD_MAX_LENGTH: number = 20
    /**
     输入框内边距
     */
    static readonly TEXT_INPUT_PADDING: string = '12vp'
    /**
     * 输入框外边距
     */
    static readonly TEXT_INPUT_MARGIN: string = '10vp'
    /**
     * 外边距
     */
    static readonly MARGIN_NORMAL: string = '20vp'
    static readonly MARGIN_LESS: string = '10vp'
    static readonly MARGIN_MORE: string = '30vp'
    /**
     * 宽度
     */
    static readonly WIDTH_NORMAL: string = '80%'
    static readonly WIDTH_FULL: string = '100%'
}